# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSACES_OpManagement_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OpManagement(object):
    def setupUi(self, OpManagement):
        OpManagement.setObjectName("OpManagement")
        OpManagement.resize(1126, 859)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OpManagement.sizePolicy().hasHeightForWidth())
        OpManagement.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Script/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OpManagement.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(OpManagement)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(OpManagement)
        self.tabWidget.setMinimumSize(QtCore.QSize(1101, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TableOperation = QtWidgets.QTableWidget(self.tab)
        self.TableOperation.setMinimumSize(QtCore.QSize(1069, 761))
        self.TableOperation.setMaximumSize(QtCore.QSize(1069, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TableOperation.setFont(font)
        self.TableOperation.setLineWidth(1)
        self.TableOperation.setAutoScrollMargin(16)
        self.TableOperation.setObjectName("TableOperation")
        self.TableOperation.setColumnCount(3)
        self.TableOperation.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableOperation.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOperation.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOperation.setHorizontalHeaderItem(2, item)
        self.TableOperation.horizontalHeader().setCascadingSectionResizes(True)
        self.TableOperation.horizontalHeader().setDefaultSectionSize(370)
        self.TableOperation.horizontalHeader().setStretchLastSection(True)
        self.TableOperation.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_2.addWidget(self.TableOperation, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LE_ChooseOP = QtWidgets.QLineEdit(self.tab_2)
        self.LE_ChooseOP.setObjectName("LE_ChooseOP")
        self.gridLayout_3.addWidget(self.LE_ChooseOP, 1, 2, 1, 1)
        self.TableEditOp = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableEditOp.sizePolicy().hasHeightForWidth())
        self.TableEditOp.setSizePolicy(sizePolicy)
        self.TableEditOp.setMinimumSize(QtCore.QSize(1000, 500))
        self.TableEditOp.setMaximumSize(QtCore.QSize(1100, 712))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TableEditOp.setFont(font)
        self.TableEditOp.setDragEnabled(True)
        self.TableEditOp.setShowGrid(True)
        self.TableEditOp.setWordWrap(True)
        self.TableEditOp.setObjectName("TableEditOp")
        self.TableEditOp.setColumnCount(5)
        self.TableEditOp.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEditOp.setHorizontalHeaderItem(4, item)
        self.TableEditOp.horizontalHeader().setCascadingSectionResizes(True)
        self.TableEditOp.horizontalHeader().setDefaultSectionSize(170)
        self.TableEditOp.horizontalHeader().setStretchLastSection(True)
        self.TableEditOp.verticalHeader().setCascadingSectionResizes(True)
        self.TableEditOp.verticalHeader().setDefaultSectionSize(40)
        self.TableEditOp.verticalHeader().setMinimumSectionSize(30)
        self.TableEditOp.verticalHeader().setSortIndicatorShown(False)
        self.TableEditOp.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.TableEditOp, 5, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 20, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LookUpEditOp = QtWidgets.QPushButton(self.tab_2)
        self.LookUpEditOp.setWhatsThis("")
        self.LookUpEditOp.setObjectName("LookUpEditOp")
        self.horizontalLayout.addWidget(self.LookUpEditOp)
        self.FillColumn = QtWidgets.QPushButton(self.tab_2)
        self.FillColumn.setWhatsThis("")
        self.FillColumn.setObjectName("FillColumn")
        self.horizontalLayout.addWidget(self.FillColumn)
        self.FillRow = QtWidgets.QPushButton(self.tab_2)
        self.FillRow.setWhatsThis("")
        self.FillRow.setObjectName("FillRow")
        self.horizontalLayout.addWidget(self.FillRow)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.EditNameLabel = QtWidgets.QLabel(self.groupBox)
        self.EditNameLabel.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.EditNameLabel.setObjectName("EditNameLabel")
        self.EditName = QtWidgets.QLineEdit(self.groupBox)
        self.EditName.setGeometry(QtCore.QRect(120, 30, 221, 22))
        self.EditName.setObjectName("EditName")
        self.EditMinimumLabel = QtWidgets.QLabel(self.groupBox)
        self.EditMinimumLabel.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.EditMinimumLabel.setObjectName("EditMinimumLabel")
        self.EditMin = QtWidgets.QLineEdit(self.groupBox)
        self.EditMin.setGeometry(QtCore.QRect(120, 70, 111, 22))
        self.EditMin.setObjectName("EditMin")
        self.saveEdit = QtWidgets.QPushButton(self.groupBox)
        self.saveEdit.setGeometry(QtCore.QRect(670, 70, 101, 31))
        self.saveEdit.setObjectName("saveEdit")
        self.EditOpLabel = QtWidgets.QLabel(self.groupBox)
        self.EditOpLabel.setGeometry(QtCore.QRect(380, 30, 55, 16))
        self.EditOpLabel.setObjectName("EditOpLabel")
        self.EditUnitLabel = QtWidgets.QLabel(self.groupBox)
        self.EditUnitLabel.setGeometry(QtCore.QRect(380, 70, 55, 16))
        self.EditUnitLabel.setObjectName("EditUnitLabel")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(670, 20, 391, 31))
        self.label_6.setObjectName("label_6")
        self.EditOp = QtWidgets.QLineEdit(self.groupBox)
        self.EditOp.setGeometry(QtCore.QRect(430, 30, 113, 22))
        self.EditOp.setReadOnly(True)
        self.EditOp.setObjectName("EditOp")
        self.EditUnit = QtWidgets.QLineEdit(self.groupBox)
        self.EditUnit.setGeometry(QtCore.QRect(430, 70, 113, 22))
        self.EditUnit.setObjectName("EditUnit")
        self.gridLayout_3.addWidget(self.groupBox, 6, 1, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setMinimumSize(QtCore.QSize(111, 31))
        self.label_2.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.LE_OpNumber = QtWidgets.QLineEdit(self.tab_3)
        self.LE_OpNumber.setMinimumSize(QtCore.QSize(250, 41))
        self.LE_OpNumber.setMaximumSize(QtCore.QSize(250, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_OpNumber.setFont(font)
        self.LE_OpNumber.setObjectName("LE_OpNumber")
        self.gridLayout_4.addWidget(self.LE_OpNumber, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setMinimumSize(QtCore.QSize(121, 31))
        self.label_4.setMaximumSize(QtCore.QSize(121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 2, 1, 1)
        self.LE_OpMin = QtWidgets.QLineEdit(self.tab_3)
        self.LE_OpMin.setMinimumSize(QtCore.QSize(121, 41))
        self.LE_OpMin.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_OpMin.setFont(font)
        self.LE_OpMin.setObjectName("LE_OpMin")
        self.gridLayout_4.addWidget(self.LE_OpMin, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMinimumSize(QtCore.QSize(101, 31))
        self.label_3.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.LE_OpName = QtWidgets.QLineEdit(self.tab_3)
        self.LE_OpName.setMinimumSize(QtCore.QSize(250, 41))
        self.LE_OpName.setMaximumSize(QtCore.QSize(250, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_OpName.setFont(font)
        self.LE_OpName.setObjectName("LE_OpName")
        self.gridLayout_4.addWidget(self.LE_OpName, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setMinimumSize(QtCore.QSize(61, 31))
        self.label_5.setMaximumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 2, 1, 1)
        self.TableNewOp = QtWidgets.QTableWidget(self.tab_3)
        self.TableNewOp.setMinimumSize(QtCore.QSize(1071, 541))
        self.TableNewOp.setMaximumSize(QtCore.QSize(1071, 541))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TableNewOp.setFont(font)
        self.TableNewOp.setAlternatingRowColors(True)
        self.TableNewOp.setGridStyle(QtCore.Qt.CustomDashLine)
        self.TableNewOp.setObjectName("TableNewOp")
        self.TableNewOp.setColumnCount(6)
        self.TableNewOp.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableNewOp.setHorizontalHeaderItem(5, item)
        self.TableNewOp.horizontalHeader().setStretchLastSection(True)
        self.TableNewOp.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.TableNewOp, 2, 0, 1, 5)
        self.PB_ValidateNewOp = QtWidgets.QPushButton(self.tab_3)
        self.PB_ValidateNewOp.setMinimumSize(QtCore.QSize(141, 41))
        self.PB_ValidateNewOp.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_ValidateNewOp.setFont(font)
        self.PB_ValidateNewOp.setStyleSheet("")
        self.PB_ValidateNewOp.setObjectName("PB_ValidateNewOp")
        self.gridLayout_4.addWidget(self.PB_ValidateNewOp, 3, 4, 1, 1)
        self.LE_UnitOp = QtWidgets.QComboBox(self.tab_3)
        self.LE_UnitOp.setObjectName("LE_UnitOp")
        self.gridLayout_4.addWidget(self.LE_UnitOp, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(OpManagement)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OpManagement)

    def retranslateUi(self, OpManagement):
        _translate = QtCore.QCoreApplication.translate
        OpManagement.setWindowTitle(_translate("OpManagement", "Operation Management"))
        item = self.TableOperation.horizontalHeaderItem(0)
        item.setText(_translate("OpManagement", "Number"))
        item = self.TableOperation.horizontalHeaderItem(1)
        item.setText(_translate("OpManagement", "Operation Name"))
        item = self.TableOperation.horizontalHeaderItem(2)
        item.setText(_translate("OpManagement", "Minimum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OpManagement", "Operations"))
        self.LE_ChooseOP.setToolTip(_translate("OpManagement", "Hit ENTER or Look Up Item"))
        item = self.TableEditOp.verticalHeaderItem(0)
        item.setText(_translate("OpManagement", "x < 0.189"))
        item = self.TableEditOp.verticalHeaderItem(1)
        item.setText(_translate("OpManagement", "0.189 < x < 0.251"))
        item = self.TableEditOp.verticalHeaderItem(2)
        item.setText(_translate("OpManagement", "0.251 < x < 0.376"))
        item = self.TableEditOp.verticalHeaderItem(3)
        item.setText(_translate("OpManagement", "0.376 < x < 0.501"))
        item = self.TableEditOp.verticalHeaderItem(4)
        item.setText(_translate("OpManagement", "0.501 < x < 0.626"))
        item = self.TableEditOp.verticalHeaderItem(5)
        item.setText(_translate("OpManagement", "0.626 < x < 0.751"))
        item = self.TableEditOp.verticalHeaderItem(6)
        item.setText(_translate("OpManagement", "0.751 < x < 0.876"))
        item = self.TableEditOp.verticalHeaderItem(7)
        item.setText(_translate("OpManagement", "0.876 < x < 1.001"))
        item = self.TableEditOp.verticalHeaderItem(8)
        item.setText(_translate("OpManagement", "1.001 < x < 1.126"))
        item = self.TableEditOp.verticalHeaderItem(9)
        item.setText(_translate("OpManagement", "1.126 < x"))
        item = self.TableEditOp.verticalHeaderItem(10)
        item.setText(_translate("OpManagement", "Set Up Cost"))
        item = self.TableEditOp.horizontalHeaderItem(0)
        item.setText(_translate("OpManagement", "B"))
        item = self.TableEditOp.horizontalHeaderItem(1)
        item.setText(_translate("OpManagement", "C"))
        item = self.TableEditOp.horizontalHeaderItem(2)
        item.setText(_translate("OpManagement", "D"))
        item = self.TableEditOp.horizontalHeaderItem(3)
        item.setText(_translate("OpManagement", "E"))
        item = self.TableEditOp.horizontalHeaderItem(4)
        item.setText(_translate("OpManagement", "F"))
        self.LookUpEditOp.setToolTip(_translate("OpManagement", "Look up item, or press Enter in the Choos Your Operation box above."))
        self.LookUpEditOp.setText(_translate("OpManagement", "Look Up Item"))
        self.FillColumn.setToolTip(_translate("OpManagement", "Fill remainder of column based on the value in the cell currently selected."))
        self.FillColumn.setText(_translate("OpManagement", "Fill Column"))
        self.FillRow.setToolTip(_translate("OpManagement", "Fill remainder of row with the value of the cell that is currently selected."))
        self.FillRow.setText(_translate("OpManagement", "Fill Row"))
        self.label.setText(_translate("OpManagement", "Choose your operation :"))
        self.groupBox.setTitle(_translate("OpManagement", "GroupBox"))
        self.EditNameLabel.setText(_translate("OpManagement", "Edit Name"))
        self.EditMinimumLabel.setText(_translate("OpManagement", "Edit  Minimum"))
        self.saveEdit.setText(_translate("OpManagement", "Save Changes"))
        self.EditOpLabel.setText(_translate("OpManagement", "OP#"))
        self.EditUnitLabel.setText(_translate("OpManagement", "Unit"))
        self.label_6.setText(_translate("OpManagement", "Double Click Grid above, or Save Changes Below to Save"))
        self.EditOp.setToolTip(_translate("OpManagement", "<html><head/><body><p><br/></p></body></html>"))
        self.EditUnit.setToolTip(_translate("OpManagement", "pc or lb"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OpManagement", "Edit Operation Cost"))
        self.label_2.setText(_translate("OpManagement", "Number :"))
        self.label_4.setText(_translate("OpManagement", "Minimum :"))
        self.label_3.setText(_translate("OpManagement", "Name :"))
        self.label_5.setText(_translate("OpManagement", "Unit :"))
        item = self.TableNewOp.verticalHeaderItem(0)
        item.setText(_translate("OpManagement", "x < 0.189"))
        item = self.TableNewOp.verticalHeaderItem(1)
        item.setText(_translate("OpManagement", "0.189 < x < 0.251"))
        item = self.TableNewOp.verticalHeaderItem(2)
        item.setText(_translate("OpManagement", "0.251 < x < 0.376"))
        item = self.TableNewOp.verticalHeaderItem(3)
        item.setText(_translate("OpManagement", "0.376 < x < 0.501"))
        item = self.TableNewOp.verticalHeaderItem(4)
        item.setText(_translate("OpManagement", "0.501 < x < 0.626"))
        item = self.TableNewOp.verticalHeaderItem(5)
        item.setText(_translate("OpManagement", "0.626 < x < 0.751"))
        item = self.TableNewOp.verticalHeaderItem(6)
        item.setText(_translate("OpManagement", "0.751 < x < 0.876"))
        item = self.TableNewOp.verticalHeaderItem(7)
        item.setText(_translate("OpManagement", "0.876 < x < 1.001"))
        item = self.TableNewOp.verticalHeaderItem(8)
        item.setText(_translate("OpManagement", "1.001 < x < 1.126"))
        item = self.TableNewOp.verticalHeaderItem(9)
        item.setText(_translate("OpManagement", "1.126 < x"))
        item = self.TableNewOp.verticalHeaderItem(10)
        item.setText(_translate("OpManagement", "Set Up Cost"))
        item = self.TableNewOp.horizontalHeaderItem(0)
        item.setText(_translate("OpManagement", "B"))
        item = self.TableNewOp.horizontalHeaderItem(1)
        item.setText(_translate("OpManagement", "C"))
        item = self.TableNewOp.horizontalHeaderItem(2)
        item.setText(_translate("OpManagement", "D"))
        item = self.TableNewOp.horizontalHeaderItem(3)
        item.setText(_translate("OpManagement", "E"))
        item = self.TableNewOp.horizontalHeaderItem(4)
        item.setText(_translate("OpManagement", "F"))
        item = self.TableNewOp.horizontalHeaderItem(5)
        item.setText(_translate("OpManagement", "Unit"))
        self.PB_ValidateNewOp.setText(_translate("OpManagement", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("OpManagement", "Add New Operation"))

