# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSACES_MM_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MaterialManagement(object):
    def setupUi(self, MaterialManagement):
        MaterialManagement.setObjectName("MaterialManagement")
        MaterialManagement.resize(1429, 713)
        MaterialManagement.setMinimumSize(QtCore.QSize(1429, 713))
        MaterialManagement.setMaximumSize(QtCore.QSize(1429, 713))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Script/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MaterialManagement.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(MaterialManagement)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1411, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1091, 631))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 241, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableMM = QtWidgets.QTableWidget(self.groupBox)
        self.tableMM.setGeometry(QtCore.QRect(20, 90, 1051, 531))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableMM.setFont(font)
        self.tableMM.setObjectName("tableMM")
        self.tableMM.setColumnCount(7)
        self.tableMM.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMM.setHorizontalHeaderItem(6, item)
        self.LE_MatName = QtWidgets.QLineEdit(self.groupBox)
        self.LE_MatName.setGeometry(QtCore.QRect(270, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LE_MatName.setFont(font)
        self.LE_MatName.setObjectName("LE_MatName")
        self.PB_EnterMat = QtWidgets.QPushButton(self.groupBox)
        self.PB_EnterMat.setGeometry(QtCore.QRect(650, 30, 71, 41))
        self.PB_EnterMat.setObjectName("PB_EnterMat")
        self.PB_ShowAll = QtWidgets.QPushButton(self.groupBox)
        self.PB_ShowAll.setGeometry(QtCore.QRect(740, 30, 101, 41))
        self.PB_ShowAll.setObjectName("PB_ShowAll")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(1110, 10, 291, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.LE_SetAllCost = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_SetAllCost.setGeometry(QtCore.QRect(150, 40, 81, 31))
        self.LE_SetAllCost.setObjectName("LE_SetAllCost")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(240, 50, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.PB_SetAllCost = QtWidgets.QPushButton(self.groupBox_2)
        self.PB_SetAllCost.setGeometry(QtCore.QRect(170, 90, 112, 34))
        self.PB_SetAllCost.setObjectName("PB_SetAllCost")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(1110, 160, 291, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 121, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LE_SetFromTo = QtWidgets.QLineEdit(self.groupBox_3)
        self.LE_SetFromTo.setGeometry(QtCore.QRect(140, 40, 81, 31))
        self.LE_SetFromTo.setObjectName("LE_SetFromTo")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(240, 50, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.PB_SetFromTo = QtWidgets.QPushButton(self.groupBox_3)
        self.PB_SetFromTo.setGeometry(QtCore.QRect(170, 130, 112, 34))
        self.PB_SetFromTo.setObjectName("PB_SetFromTo")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.LE_SetFromDiam = QtWidgets.QLineEdit(self.groupBox_3)
        self.LE_SetFromDiam.setGeometry(QtCore.QRect(70, 90, 81, 31))
        self.LE_SetFromDiam.setObjectName("LE_SetFromDiam")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(160, 100, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.LE_SetToDiam = QtWidgets.QLineEdit(self.groupBox_3)
        self.LE_SetToDiam.setGeometry(QtCore.QRect(200, 90, 81, 31))
        self.LE_SetToDiam.setObjectName("LE_SetToDiam")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(1110, 360, 291, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(749, 393))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_4.setPalette(palette)
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.LE_RawNumber = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_RawNumber.setFont(font)
        self.LE_RawNumber.setObjectName("LE_RawNumber")
        self.gridLayout_2.addWidget(self.LE_RawNumber, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.LE_RawName = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_RawName.setFont(font)
        self.LE_RawName.setObjectName("LE_RawName")
        self.gridLayout_2.addWidget(self.LE_RawName, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.LE_RawSpec = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_RawSpec.setFont(font)
        self.LE_RawSpec.setObjectName("LE_RawSpec")
        self.gridLayout_2.addWidget(self.LE_RawSpec, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.CB_Type = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CB_Type.setFont(font)
        self.CB_Type.setObjectName("CB_Type")
        self.CB_Type.addItem("")
        self.CB_Type.addItem("")
        self.CB_Type.addItem("")
        self.CB_Type.addItem("")
        self.gridLayout_2.addWidget(self.CB_Type, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.CB_Form = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CB_Form.setFont(font)
        self.CB_Form.setObjectName("CB_Form")
        self.CB_Form.addItem("")
        self.CB_Form.addItem("")
        self.CB_Form.addItem("")
        self.gridLayout_2.addWidget(self.CB_Form, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.CB_Group = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CB_Group.setFont(font)
        self.CB_Group.setObjectName("CB_Group")
        self.CB_Group.addItem("")
        self.CB_Group.addItem("")
        self.CB_Group.addItem("")
        self.CB_Group.addItem("")
        self.CB_Group.addItem("")
        self.gridLayout_2.addWidget(self.CB_Group, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.LE_RawDiam = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_RawDiam.setFont(font)
        self.LE_RawDiam.setObjectName("LE_RawDiam")
        self.gridLayout_2.addWidget(self.LE_RawDiam, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 2, 1, 1)
        self.LE_RawCost = QtWidgets.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_RawCost.setFont(font)
        self.LE_RawCost.setObjectName("LE_RawCost")
        self.gridLayout_2.addWidget(self.LE_RawCost, 4, 3, 1, 1)
        self.PB_NewRawMat = QtWidgets.QPushButton(self.groupBox_4)
        self.PB_NewRawMat.setMaximumSize(QtCore.QSize(180, 16777215))
        self.PB_NewRawMat.setObjectName("PB_NewRawMat")
        self.gridLayout_2.addWidget(self.PB_NewRawMat, 5, 3, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MaterialManagement)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MaterialManagement)

    def retranslateUi(self, MaterialManagement):
        _translate = QtCore.QCoreApplication.translate
        MaterialManagement.setWindowTitle(_translate("MaterialManagement", "Material Management"))
        self.groupBox.setTitle(_translate("MaterialManagement", "Material Information"))
        self.label.setText(_translate("MaterialManagement", "Enter Material Name : "))
        item = self.tableMM.horizontalHeaderItem(0)
        item.setText(_translate("MaterialManagement", "Number"))
        item = self.tableMM.horizontalHeaderItem(1)
        item.setText(_translate("MaterialManagement", "Diam"))
        item = self.tableMM.horizontalHeaderItem(2)
        item.setText(_translate("MaterialManagement", "Cost"))
        item = self.tableMM.horizontalHeaderItem(3)
        item.setText(_translate("MaterialManagement", "Spec"))
        item = self.tableMM.horizontalHeaderItem(4)
        item.setText(_translate("MaterialManagement", "Type"))
        item = self.tableMM.horizontalHeaderItem(5)
        item.setText(_translate("MaterialManagement", "Form"))
        item = self.tableMM.horizontalHeaderItem(6)
        item.setText(_translate("MaterialManagement", "Groupe"))
        self.PB_EnterMat.setText(_translate("MaterialManagement", "Select"))
        self.PB_ShowAll.setText(_translate("MaterialManagement", "Show All"))
        self.groupBox_2.setTitle(_translate("MaterialManagement", "Edit all cost :"))
        self.label_2.setText(_translate("MaterialManagement", "Set costs to : "))
        self.label_3.setText(_translate("MaterialManagement", "/ lbs"))
        self.PB_SetAllCost.setText(_translate("MaterialManagement", "Validate"))
        self.groupBox_3.setTitle(_translate("MaterialManagement", "Edit range of diameter :"))
        self.label_4.setText(_translate("MaterialManagement", "Set costs to : "))
        self.label_5.setText(_translate("MaterialManagement", "/ lbs"))
        self.PB_SetFromTo.setText(_translate("MaterialManagement", "Validate"))
        self.label_6.setText(_translate("MaterialManagement", "From :"))
        self.label_7.setText(_translate("MaterialManagement", "To :"))
        self.textBrowser.setHtml(_translate("MaterialManagement", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find correct material.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Change values by clicking <span style=\" font-weight:600;\">once</span>, then typing changes.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Double</span> click on <span style=\" font-weight:600; font-style:italic;\">EACH</span> cell save data.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MaterialManagement", "Edit Raw Material"))
        self.groupBox_4.setTitle(_translate("MaterialManagement", "Add Raw Material"))
        self.label_8.setText(_translate("MaterialManagement", "Number :"))
        self.label_9.setText(_translate("MaterialManagement", "Name :"))
        self.label_10.setText(_translate("MaterialManagement", "Spec :"))
        self.label_11.setText(_translate("MaterialManagement", "Type :"))
        self.CB_Type.setItemText(0, _translate("MaterialManagement", "Steel"))
        self.CB_Type.setItemText(1, _translate("MaterialManagement", "NiBase"))
        self.CB_Type.setItemText(2, _translate("MaterialManagement", "Alum"))
        self.CB_Type.setItemText(3, _translate("MaterialManagement", "Titan"))
        self.label_12.setText(_translate("MaterialManagement", "Form :"))
        self.CB_Form.setItemText(0, _translate("MaterialManagement", "Bar"))
        self.CB_Form.setItemText(1, _translate("MaterialManagement", "Coil"))
        self.CB_Form.setItemText(2, _translate("MaterialManagement", "Hex"))
        self.label_13.setText(_translate("MaterialManagement", "Group :"))
        self.CB_Group.setItemText(0, _translate("MaterialManagement", "B"))
        self.CB_Group.setItemText(1, _translate("MaterialManagement", "C"))
        self.CB_Group.setItemText(2, _translate("MaterialManagement", "D"))
        self.CB_Group.setItemText(3, _translate("MaterialManagement", "E"))
        self.CB_Group.setItemText(4, _translate("MaterialManagement", "F"))
        self.label_14.setText(_translate("MaterialManagement", "Diameter :"))
        self.label_15.setText(_translate("MaterialManagement", "Cost :"))
        self.PB_NewRawMat.setText(_translate("MaterialManagement", "Add Material"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MaterialManagement", "Add Raw Material"))

