# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSACES_QUOTE_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

###09/19/19 - Added logic to output more information on quotes - date created, part creator, quote creator
###09/26/19 - Add logic for NUTS, STUDS in addition to original BOLTS
### NUTS = 2.0 HDVOL, BOLTS 2.2, STUDS = 0.0x
### NUTS = 0.0 SHANK length, BOlts = regular, Studs = Regular

##Split Quote_UI (PyQt designer) in this file, remaining main stuff into MSACES_quote.py
##When you use PyQt Designer this file gets overwritten and destroyed. Not a good way to build a program.
##Also compartmentalizing code into separate files is better, more readable, and more testable

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QCompleter
from PyQt5.QtWidgets import QLineEdit
from PyQt5.QtWidgets import QApplication

from math import pi
import xlsxwriter
from datetime import datetime

#import sqlite3   #connectSQLite from MSACES should be used
import os
import traceback
#from MSACES import *
# import MSACES
#from MSACES import connectSQLite, closeSQLite #connectSQLite doesn't work..?
import getpass

import re

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
    
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Quote(object):
    def setupUi(self, Quote):
        Quote.setObjectName("Quote")
        Quote.resize(1041, 718)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Quote.sizePolicy().hasHeightForWidth())
        Quote.setSizePolicy(sizePolicy)
        Quote.setMinimumSize(QtCore.QSize(889, 515))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Script/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Quote.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(Quote)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Quote)
        self.groupBox.setMinimumSize(QtCore.QSize(861, 441))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.TableQuote = QtWidgets.QTableWidget(self.groupBox)
        self.TableQuote.setAlternatingRowColors(True)
        self.TableQuote.setObjectName("TableQuote")
        self.TableQuote.setColumnCount(12)
        self.TableQuote.setRowCount(100)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(64, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(65, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(66, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(67, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(68, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(69, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(70, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(71, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(72, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(73, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(74, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(75, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(76, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(77, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(78, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(79, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(80, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(81, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(82, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(83, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(84, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(85, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(86, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(87, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(88, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(89, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(90, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(91, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(92, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(93, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(94, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(95, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(96, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(97, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(98, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setVerticalHeaderItem(99, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableQuote.setHorizontalHeaderItem(11, item)
        self.TableQuote.horizontalHeader().setDefaultSectionSize(170)
        self.gridLayout.addWidget(self.TableQuote, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.Action = QtWidgets.QGroupBox(Quote)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Action.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Action.setFont(font)
        self.Action.setAutoFillBackground(True)
        self.Action.setObjectName("Action")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Action)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_Quote = QtWidgets.QPushButton(self.Action)
        self.PB_Quote.setMinimumSize(QtCore.QSize(181, 41))
        self.PB_Quote.setMaximumSize(QtCore.QSize(181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_Quote.setFont(font)
        self.PB_Quote.setObjectName("PB_Quote")
        self.horizontalLayout.addWidget(self.PB_Quote)
        self.PB_CopyPaste = QtWidgets.QPushButton(self.Action)
        self.PB_CopyPaste.setMinimumSize(QtCore.QSize(181, 41))
        self.PB_CopyPaste.setMaximumSize(QtCore.QSize(181, 41))
        self.PB_CopyPaste.setObjectName("PB_CopyPaste")
        self.horizontalLayout.addWidget(self.PB_CopyPaste)
        self.PB_EraseForPaste = QtWidgets.QPushButton(self.Action)
        self.PB_EraseForPaste.setEnabled(True)
        self.PB_EraseForPaste.setMinimumSize(QtCore.QSize(181, 41))
        self.PB_EraseForPaste.setMaximumSize(QtCore.QSize(181, 41))
        self.PB_EraseForPaste.setObjectName("PB_EraseForPaste")
        self.horizontalLayout.addWidget(self.PB_EraseForPaste)
        self.PB_ClearContent = QtWidgets.QPushButton(self.Action)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_ClearContent.sizePolicy().hasHeightForWidth())
        self.PB_ClearContent.setSizePolicy(sizePolicy)
        self.PB_ClearContent.setMinimumSize(QtCore.QSize(181, 41))
        self.PB_ClearContent.setMaximumSize(QtCore.QSize(181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_ClearContent.setFont(font)
        self.PB_ClearContent.setObjectName("PB_ClearContent")
        self.horizontalLayout.addWidget(self.PB_ClearContent)
        self.gridLayout_3.addWidget(self.Action, 1, 0, 1, 1)
        # Quote.WindowMinimizeButtonHint()

        ##https://stackoverflow.com/questions/22187207/pyqt-dialogs-minimize-window-button-is-missing-in-osx
        ##Minimize and maximize buttons -> WindowMinMaxButtonsHint
        Quote.setWindowFlags(Quote.windowFlags() |
        QtCore.Qt.WindowMinMaxButtonsHint  |
        QtCore.Qt.WindowSystemMenuHint)


        self.retranslateUi(Quote)
        QtCore.QMetaObject.connectSlotsByName(Quote)

    def retranslateUi(self, Quote):
        _translate = QtCore.QCoreApplication.translate
        Quote.setWindowTitle(_translate("Quote", "Quote"))
        self.groupBox.setTitle(_translate("Quote", "Quotation Info :"))
        item = self.TableQuote.verticalHeaderItem(0)
        item.setText(_translate("Quote", "1"))
        item = self.TableQuote.verticalHeaderItem(1)
        item.setText(_translate("Quote", "2"))
        item = self.TableQuote.verticalHeaderItem(2)
        item.setText(_translate("Quote", "3"))
        item = self.TableQuote.verticalHeaderItem(3)
        item.setText(_translate("Quote", "4"))
        item = self.TableQuote.verticalHeaderItem(4)
        item.setText(_translate("Quote", "5"))
        item = self.TableQuote.verticalHeaderItem(5)
        item.setText(_translate("Quote", "6"))
        item = self.TableQuote.verticalHeaderItem(6)
        item.setText(_translate("Quote", "7"))
        item = self.TableQuote.verticalHeaderItem(7)
        item.setText(_translate("Quote", "8"))
        item = self.TableQuote.verticalHeaderItem(8)
        item.setText(_translate("Quote", "9"))
        item = self.TableQuote.verticalHeaderItem(9)
        item.setText(_translate("Quote", "10"))
        item = self.TableQuote.verticalHeaderItem(10)
        item.setText(_translate("Quote", "11"))
        item = self.TableQuote.verticalHeaderItem(11)
        item.setText(_translate("Quote", "12"))
        item = self.TableQuote.verticalHeaderItem(12)
        item.setText(_translate("Quote", "13"))
        item = self.TableQuote.verticalHeaderItem(13)
        item.setText(_translate("Quote", "14"))
        item = self.TableQuote.verticalHeaderItem(14)
        item.setText(_translate("Quote", "15"))
        item = self.TableQuote.verticalHeaderItem(15)
        item.setText(_translate("Quote", "16"))
        item = self.TableQuote.verticalHeaderItem(16)
        item.setText(_translate("Quote", "17"))
        item = self.TableQuote.verticalHeaderItem(17)
        item.setText(_translate("Quote", "18"))
        item = self.TableQuote.verticalHeaderItem(18)
        item.setText(_translate("Quote", "19"))
        item = self.TableQuote.verticalHeaderItem(19)
        item.setText(_translate("Quote", "20"))
        item = self.TableQuote.verticalHeaderItem(20)
        item.setText(_translate("Quote", "21"))
        item = self.TableQuote.verticalHeaderItem(21)
        item.setText(_translate("Quote", "22"))
        item = self.TableQuote.verticalHeaderItem(22)
        item.setText(_translate("Quote", "23"))
        item = self.TableQuote.verticalHeaderItem(23)
        item.setText(_translate("Quote", "24"))
        item = self.TableQuote.verticalHeaderItem(24)
        item.setText(_translate("Quote", "25"))
        item = self.TableQuote.verticalHeaderItem(25)
        item.setText(_translate("Quote", "26"))
        item = self.TableQuote.verticalHeaderItem(26)
        item.setText(_translate("Quote", "27"))
        item = self.TableQuote.verticalHeaderItem(27)
        item.setText(_translate("Quote", "28"))
        item = self.TableQuote.verticalHeaderItem(28)
        item.setText(_translate("Quote", "29"))
        item = self.TableQuote.verticalHeaderItem(29)
        item.setText(_translate("Quote", "30"))
        item = self.TableQuote.verticalHeaderItem(30)
        item.setText(_translate("Quote", "31"))
        item = self.TableQuote.verticalHeaderItem(31)
        item.setText(_translate("Quote", "32"))
        item = self.TableQuote.verticalHeaderItem(32)
        item.setText(_translate("Quote", "33"))
        item = self.TableQuote.verticalHeaderItem(33)
        item.setText(_translate("Quote", "34"))
        item = self.TableQuote.verticalHeaderItem(34)
        item.setText(_translate("Quote", "35"))
        item = self.TableQuote.verticalHeaderItem(35)
        item.setText(_translate("Quote", "36"))
        item = self.TableQuote.verticalHeaderItem(36)
        item.setText(_translate("Quote", "37"))
        item = self.TableQuote.verticalHeaderItem(37)
        item.setText(_translate("Quote", "38"))
        item = self.TableQuote.verticalHeaderItem(38)
        item.setText(_translate("Quote", "39"))
        item = self.TableQuote.verticalHeaderItem(39)
        item.setText(_translate("Quote", "40"))
        item = self.TableQuote.verticalHeaderItem(40)
        item.setText(_translate("Quote", "41"))
        item = self.TableQuote.verticalHeaderItem(41)
        item.setText(_translate("Quote", "42"))
        item = self.TableQuote.verticalHeaderItem(42)
        item.setText(_translate("Quote", "43"))
        item = self.TableQuote.verticalHeaderItem(43)
        item.setText(_translate("Quote", "44"))
        item = self.TableQuote.verticalHeaderItem(44)
        item.setText(_translate("Quote", "45"))
        item = self.TableQuote.verticalHeaderItem(45)
        item.setText(_translate("Quote", "46"))
        item = self.TableQuote.verticalHeaderItem(46)
        item.setText(_translate("Quote", "47"))
        item = self.TableQuote.verticalHeaderItem(47)
        item.setText(_translate("Quote", "48"))
        item = self.TableQuote.verticalHeaderItem(48)
        item.setText(_translate("Quote", "49"))
        item = self.TableQuote.verticalHeaderItem(49)
        item.setText(_translate("Quote", "50"))
        item = self.TableQuote.verticalHeaderItem(50)
        item.setText(_translate("Quote", "51"))
        item = self.TableQuote.verticalHeaderItem(51)
        item.setText(_translate("Quote", "52"))
        item = self.TableQuote.verticalHeaderItem(52)
        item.setText(_translate("Quote", "53"))
        item = self.TableQuote.verticalHeaderItem(53)
        item.setText(_translate("Quote", "54"))
        item = self.TableQuote.verticalHeaderItem(54)
        item.setText(_translate("Quote", "55"))
        item = self.TableQuote.verticalHeaderItem(55)
        item.setText(_translate("Quote", "56"))
        item = self.TableQuote.verticalHeaderItem(56)
        item.setText(_translate("Quote", "57"))
        item = self.TableQuote.verticalHeaderItem(57)
        item.setText(_translate("Quote", "58"))
        item = self.TableQuote.verticalHeaderItem(58)
        item.setText(_translate("Quote", "59"))
        item = self.TableQuote.verticalHeaderItem(59)
        item.setText(_translate("Quote", "60"))
        item = self.TableQuote.verticalHeaderItem(60)
        item.setText(_translate("Quote", "61"))
        item = self.TableQuote.verticalHeaderItem(61)
        item.setText(_translate("Quote", "62"))
        item = self.TableQuote.verticalHeaderItem(62)
        item.setText(_translate("Quote", "63"))
        item = self.TableQuote.verticalHeaderItem(63)
        item.setText(_translate("Quote", "64"))
        item = self.TableQuote.verticalHeaderItem(64)
        item.setText(_translate("Quote", "65"))
        item = self.TableQuote.verticalHeaderItem(65)
        item.setText(_translate("Quote", "66"))
        item = self.TableQuote.verticalHeaderItem(66)
        item.setText(_translate("Quote", "67"))
        item = self.TableQuote.verticalHeaderItem(67)
        item.setText(_translate("Quote", "68"))
        item = self.TableQuote.verticalHeaderItem(68)
        item.setText(_translate("Quote", "69"))
        item = self.TableQuote.verticalHeaderItem(69)
        item.setText(_translate("Quote", "70"))
        item = self.TableQuote.verticalHeaderItem(70)
        item.setText(_translate("Quote", "71"))
        item = self.TableQuote.verticalHeaderItem(71)
        item.setText(_translate("Quote", "72"))
        item = self.TableQuote.verticalHeaderItem(72)
        item.setText(_translate("Quote", "73"))
        item = self.TableQuote.verticalHeaderItem(73)
        item.setText(_translate("Quote", "74"))
        item = self.TableQuote.verticalHeaderItem(74)
        item.setText(_translate("Quote", "75"))
        item = self.TableQuote.verticalHeaderItem(75)
        item.setText(_translate("Quote", "76"))
        item = self.TableQuote.verticalHeaderItem(76)
        item.setText(_translate("Quote", "77"))
        item = self.TableQuote.verticalHeaderItem(77)
        item.setText(_translate("Quote", "78"))
        item = self.TableQuote.verticalHeaderItem(78)
        item.setText(_translate("Quote", "79"))
        item = self.TableQuote.verticalHeaderItem(79)
        item.setText(_translate("Quote", "80"))
        item = self.TableQuote.verticalHeaderItem(80)
        item.setText(_translate("Quote", "81"))
        item = self.TableQuote.verticalHeaderItem(81)
        item.setText(_translate("Quote", "82"))
        item = self.TableQuote.verticalHeaderItem(82)
        item.setText(_translate("Quote", "83"))
        item = self.TableQuote.verticalHeaderItem(83)
        item.setText(_translate("Quote", "84"))
        item = self.TableQuote.verticalHeaderItem(84)
        item.setText(_translate("Quote", "85"))
        item = self.TableQuote.verticalHeaderItem(85)
        item.setText(_translate("Quote", "86"))
        item = self.TableQuote.verticalHeaderItem(86)
        item.setText(_translate("Quote", "87"))
        item = self.TableQuote.verticalHeaderItem(87)
        item.setText(_translate("Quote", "88"))
        item = self.TableQuote.verticalHeaderItem(88)
        item.setText(_translate("Quote", "89"))
        item = self.TableQuote.verticalHeaderItem(89)
        item.setText(_translate("Quote", "90"))
        item = self.TableQuote.verticalHeaderItem(90)
        item.setText(_translate("Quote", "91"))
        item = self.TableQuote.verticalHeaderItem(91)
        item.setText(_translate("Quote", "92"))
        item = self.TableQuote.verticalHeaderItem(92)
        item.setText(_translate("Quote", "93"))
        item = self.TableQuote.verticalHeaderItem(93)
        item.setText(_translate("Quote", "94"))
        item = self.TableQuote.verticalHeaderItem(94)
        item.setText(_translate("Quote", "95"))
        item = self.TableQuote.verticalHeaderItem(95)
        item.setText(_translate("Quote", "96"))
        item = self.TableQuote.verticalHeaderItem(96)
        item.setText(_translate("Quote", "97"))
        item = self.TableQuote.verticalHeaderItem(97)
        item.setText(_translate("Quote", "98"))
        item = self.TableQuote.verticalHeaderItem(98)
        item.setText(_translate("Quote", "99"))
        item = self.TableQuote.verticalHeaderItem(99)
        item.setText(_translate("Quote", "100"))
        item = self.TableQuote.horizontalHeaderItem(0)
        item.setText(_translate("Quote", "Part Number"))
        item = self.TableQuote.horizontalHeaderItem(1)
        item.setText(_translate("Quote", "Price Break 1"))
        item = self.TableQuote.horizontalHeaderItem(2)
        item.setText(_translate("Quote", "Price Break 2"))
        item = self.TableQuote.horizontalHeaderItem(3)
        item.setText(_translate("Quote", "Price Break 3"))
        item = self.TableQuote.horizontalHeaderItem(4)
        item.setText(_translate("Quote", "Price Break 4"))
        item = self.TableQuote.horizontalHeaderItem(5)
        item.setText(_translate("Quote", "Price Break 5"))
        item = self.TableQuote.horizontalHeaderItem(6)
        item.setText(_translate("Quote", "Price Break 6"))
        item = self.TableQuote.horizontalHeaderItem(7)
        item.setText(_translate("Quote", "Price Break 7"))
        item = self.TableQuote.horizontalHeaderItem(8)
        item.setText(_translate("Quote", "Price Break 8"))
        item = self.TableQuote.horizontalHeaderItem(9)
        item.setText(_translate("Quote", "Price Break 9"))
        item = self.TableQuote.horizontalHeaderItem(10)
        item.setText(_translate("Quote", "Price Break 10"))
        item = self.TableQuote.horizontalHeaderItem(11)
        item.setText(_translate("Quote", "Mat Change"))
        self.Action.setTitle(_translate("Quote", "Action"))
        self.PB_Quote.setText(_translate("Quote", "Validate Quote"))
        self.PB_CopyPaste.setText(_translate("Quote", "Paste"))
        self.PB_EraseForPaste.setText(_translate("Quote", "Erase for Paste"))
        self.PB_ClearContent.setText(_translate("Quote", "Clear and Reset"))



