# -*- coding: utf-8 -*-
"""
Created on Tue Jan 21 14:43:49 2020

@author: stefflc
"""

#MSACES_NEWPART_UI.py previous
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSACES_NewPart_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewPart(object):
    def setupUi(self, NewPart):
        NewPart.setObjectName("NewPart")
        NewPart.resize(1222, 691)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewPart.sizePolicy().hasHeightForWidth())
        NewPart.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        NewPart.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("msaero.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewPart.setWindowIcon(icon)
        NewPart.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewPart)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(NewPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(1100, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(10000, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.LE_MfgSpec = QtWidgets.QLineEdit(self.groupBox)
        self.LE_MfgSpec.setMinimumSize(QtCore.QSize(151, 40))
        self.LE_MfgSpec.setMaximumSize(QtCore.QSize(151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_MfgSpec.setFont(font)
        self.LE_MfgSpec.setObjectName("LE_MfgSpec")
        self.gridLayout.addWidget(self.LE_MfgSpec, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMaximumSize(QtCore.QSize(160, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 4, 1, 1)
        self.isStudBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isStudBox.setFont(font)
        self.isStudBox.setObjectName("isStudBox")
        self.gridLayout.addWidget(self.isStudBox, 7, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setMinimumSize(QtCore.QSize(111, 19))
        self.label_18.setMaximumSize(QtCore.QSize(111, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter)
        self.LE_DescMat = QtWidgets.QLineEdit(self.groupBox)
        self.LE_DescMat.setMinimumSize(QtCore.QSize(271, 40))
        self.LE_DescMat.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_DescMat.setFont(font)
        self.LE_DescMat.setObjectName("LE_DescMat")
        self.verticalLayout_5.addWidget(self.LE_DescMat)
        self.gridLayout.addLayout(self.verticalLayout_5, 3, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMinimumSize(QtCore.QSize(51, 19))
        self.label_17.setMaximumSize(QtCore.QSize(51, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17, 0, QtCore.Qt.AlignHCenter)
        self.LE_Mat = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Mat.setEnabled(False)
        self.LE_Mat.setMinimumSize(QtCore.QSize(111, 40))
        self.LE_Mat.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Mat.setFont(font)
        self.LE_Mat.setObjectName("LE_Mat")
        self.verticalLayout_4.addWidget(self.LE_Mat, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 2, 1, 1)
        self.LE_Diam_4 = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Diam_4.setEnabled(False)
        self.LE_Diam_4.setMinimumSize(QtCore.QSize(113, 40))
        self.LE_Diam_4.setMaximumSize(QtCore.QSize(113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Diam_4.setFont(font)
        self.LE_Diam_4.setObjectName("LE_Diam_4")
        self.gridLayout.addWidget(self.LE_Diam_4, 7, 5, 1, 1)
        self.LE_Shank = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Shank.setMinimumSize(QtCore.QSize(350, 40))
        self.LE_Shank.setMaximumSize(QtCore.QSize(113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Shank.setFont(font)
        self.LE_Shank.setObjectName("LE_Shank")
        self.gridLayout.addWidget(self.LE_Shank, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.isNutBox = QtWidgets.QCheckBox(self.groupBox)
        self.isNutBox.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isNutBox.setFont(font)
        self.isNutBox.setObjectName("isNutBox")
        self.gridLayout.addWidget(self.isNutBox, 8, 3, 1, 1)
        self.LE_EstDate = QtWidgets.QLineEdit(self.groupBox)
        self.LE_EstDate.setEnabled(False)
        self.LE_EstDate.setMinimumSize(QtCore.QSize(141, 40))
        self.LE_EstDate.setMaximumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_EstDate.setFont(font)
        self.LE_EstDate.setText("")
        self.LE_EstDate.setObjectName("LE_EstDate")
        self.gridLayout.addWidget(self.LE_EstDate, 9, 5, 1, 1)
        self.LE_Diam_2 = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Diam_2.setEnabled(False)
        self.LE_Diam_2.setMinimumSize(QtCore.QSize(350, 40))
        self.LE_Diam_2.setMaximumSize(QtCore.QSize(113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Diam_2.setFont(font)
        self.LE_Diam_2.setObjectName("LE_Diam_2")
        self.gridLayout.addWidget(self.LE_Diam_2, 7, 2, 1, 1)
        self.LE_Description = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Description.setMinimumSize(QtCore.QSize(500, 40))
        self.LE_Description.setMaximumSize(QtCore.QSize(331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Description.setFont(font)
        self.LE_Description.setObjectName("LE_Description")
        self.gridLayout.addWidget(self.LE_Description, 1, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 4, 1, 1)
        self.LE_PartNumber = QtWidgets.QLineEdit(self.groupBox)
        self.LE_PartNumber.setMinimumSize(QtCore.QSize(400, 40))
        self.LE_PartNumber.setMaximumSize(QtCore.QSize(331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_PartNumber.setFont(font)
        self.LE_PartNumber.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.LE_PartNumber.setObjectName("LE_PartNumber")
        self.gridLayout.addWidget(self.LE_PartNumber, 0, 2, 1, 2)
        self.CB_HeadOp = QtWidgets.QComboBox(self.groupBox)
        self.CB_HeadOp.setMinimumSize(QtCore.QSize(151, 40))
        self.CB_HeadOp.setMaximumSize(QtCore.QSize(151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CB_HeadOp.setFont(font)
        self.CB_HeadOp.setObjectName("CB_HeadOp")
        self.CB_HeadOp.addItem("")
        self.CB_HeadOp.addItem("")
        self.CB_HeadOp.addItem("")
        self.CB_HeadOp.addItem("")
        self.CB_HeadOp.addItem("")
        self.gridLayout.addWidget(self.CB_HeadOp, 6, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(111, 21))
        self.label_7.setMaximumSize(QtCore.QSize(111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.LE_Diam = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Diam.setMinimumSize(QtCore.QSize(113, 40))
        self.LE_Diam.setMaximumSize(QtCore.QSize(113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Diam.setFont(font)
        self.LE_Diam.setObjectName("LE_Diam")
        self.verticalLayout_7.addWidget(self.LE_Diam, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_7, 3, 4, 1, 1)
        self.LE_Revision = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Revision.setMinimumSize(QtCore.QSize(81, 40))
        self.LE_Revision.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Revision.setFont(font)
        self.LE_Revision.setObjectName("LE_Revision")
        self.gridLayout.addWidget(self.LE_Revision, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.LE_Diam_3 = QtWidgets.QLineEdit(self.groupBox)
        self.LE_Diam_3.setEnabled(False)
        self.LE_Diam_3.setMinimumSize(QtCore.QSize(350, 40))
        self.LE_Diam_3.setMaximumSize(QtCore.QSize(113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_Diam_3.setFont(font)
        self.LE_Diam_3.setObjectName("LE_Diam_3")
        self.gridLayout.addWidget(self.LE_Diam_3, 8, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setMaximumSize(QtCore.QSize(160, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 4, 1, 1)
        self.CB_EstBy = QtWidgets.QComboBox(self.groupBox)
        self.CB_EstBy.setMinimumSize(QtCore.QSize(71, 40))
        self.CB_EstBy.setMaximumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CB_EstBy.setFont(font)
        self.CB_EstBy.setObjectName("CB_EstBy")
        self.CB_EstBy.addItem("")
        self.CB_EstBy.addItem("")
        self.CB_EstBy.addItem("")
        self.gridLayout.addWidget(self.CB_EstBy, 8, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.LE_Note = QtWidgets.QTextEdit(self.groupBox_3)
        self.LE_Note.setGeometry(QtCore.QRect(3, 16, 831, 61))
        self.LE_Note.setMinimumSize(QtCore.QSize(0, 20))
        self.LE_Note.setObjectName("LE_Note")
        self.gridLayout.addWidget(self.groupBox_3, 9, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(954, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setMinimumSize(QtCore.QSize(41, 19))
        self.label_14.setMaximumSize(QtCore.QSize(41, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.LE_NumeroOp = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_NumeroOp.setMinimumSize(QtCore.QSize(71, 40))
        self.LE_NumeroOp.setMaximumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_NumeroOp.setFont(font)
        self.LE_NumeroOp.setObjectName("LE_NumeroOp")
        self.verticalLayout_8.addWidget(self.LE_NumeroOp)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.TableOp = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableOp.sizePolicy().hasHeightForWidth())
        self.TableOp.setSizePolicy(sizePolicy)
        self.TableOp.setMinimumSize(QtCore.QSize(891, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TableOp.setFont(font)
        self.TableOp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableOp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TableOp.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TableOp.setAlternatingRowColors(True)
        self.TableOp.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.TableOp.setShowGrid(True)
        self.TableOp.setGridStyle(QtCore.Qt.CustomDashLine)
        self.TableOp.setObjectName("TableOp")
        self.TableOp.setColumnCount(4)
        self.TableOp.setRowCount(40)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableOp.setHorizontalHeaderItem(3, item)
        self.TableOp.horizontalHeader().setCascadingSectionResizes(True)
        self.TableOp.horizontalHeader().setDefaultSectionSize(200)
        self.TableOp.horizontalHeader().setSortIndicatorShown(False)
        self.TableOp.horizontalHeader().setStretchLastSection(True)
        self.TableOp.verticalHeader().setCascadingSectionResizes(True)
        self.TableOp.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.TableOp, 1, 0, 1, 5)
        self.PB_ValidateOperation = QtWidgets.QPushButton(self.groupBox_2)
        self.PB_ValidateOperation.setMinimumSize(QtCore.QSize(220, 41))
        self.PB_ValidateOperation.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_ValidateOperation.setFont(font)
        self.PB_ValidateOperation.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PB_ValidateOperation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ValidateOperation.setStyleSheet("")
        self.PB_ValidateOperation.setObjectName("PB_ValidateOperation")
        self.gridLayout_2.addWidget(self.PB_ValidateOperation, 2, 1, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setMinimumSize(QtCore.QSize(121, 21))
        self.label_16.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.LE_DescriptionOp = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_DescriptionOp.setMinimumSize(QtCore.QSize(401, 40))
        self.LE_DescriptionOp.setMaximumSize(QtCore.QSize(401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_DescriptionOp.setFont(font)
        self.LE_DescriptionOp.setObjectName("LE_DescriptionOp")
        self.verticalLayout_11.addWidget(self.LE_DescriptionOp)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 0, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.PB_AddOp = QtWidgets.QPushButton(self.groupBox_2)
        self.PB_AddOp.setMinimumSize(QtCore.QSize(230, 34))
        self.PB_AddOp.setMaximumSize(QtCore.QSize(161, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_AddOp.setFont(font)
        self.PB_AddOp.setObjectName("PB_AddOp")
        self.verticalLayout_12.addWidget(self.PB_AddOp, 0, QtCore.Qt.AlignHCenter)
        self.PB_RemoveOp = QtWidgets.QPushButton(self.groupBox_2)
        self.PB_RemoveOp.setMinimumSize(QtCore.QSize(230, 34))
        self.PB_RemoveOp.setMaximumSize(QtCore.QSize(161, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_RemoveOp.setFont(font)
        self.PB_RemoveOp.setObjectName("PB_RemoveOp")
        self.verticalLayout_12.addWidget(self.PB_RemoveOp)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 4, 1, 1)
        self.PB_SaveOperation = QtWidgets.QPushButton(self.groupBox_2)
        self.PB_SaveOperation.setMinimumSize(QtCore.QSize(220, 41))
        self.PB_SaveOperation.setMaximumSize(QtCore.QSize(220, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_SaveOperation.setFont(font)
        self.PB_SaveOperation.setObjectName("PB_SaveOperation")
        self.gridLayout_2.addWidget(self.PB_SaveOperation, 2, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setMinimumSize(QtCore.QSize(68, 19))
        self.label_15.setMaximumSize(QtCore.QSize(68, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.LE_CodeOp = QtWidgets.QLineEdit(self.groupBox_2)
        self.LE_CodeOp.setMinimumSize(QtCore.QSize(101, 40))
        self.LE_CodeOp.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LE_CodeOp.setFont(font)
        self.LE_CodeOp.setObjectName("LE_CodeOp")
        self.verticalLayout_10.addWidget(self.LE_CodeOp)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        ##https://stackoverflow.com/questions/22187207/pyqt-dialogs-minimize-window-button-is-missing-in-osx
        ##Minimize and maximize buttons -> WindowMinMaxButtonsHint
        NewPart.setWindowFlags(NewPart.windowFlags() |
        QtCore.Qt.WindowMinMaxButtonsHint  |
        QtCore.Qt.WindowSystemMenuHint)



        self.retranslateUi(NewPart)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NewPart)
        NewPart.setTabOrder(self.LE_PartNumber, self.LE_Revision)
        NewPart.setTabOrder(self.LE_Revision, self.LE_Description)
        NewPart.setTabOrder(self.LE_Description, self.LE_MfgSpec)
        NewPart.setTabOrder(self.LE_MfgSpec, self.LE_DescMat)
        NewPart.setTabOrder(self.LE_DescMat, self.LE_Diam)
        NewPart.setTabOrder(self.LE_Diam, self.LE_Shank)
        NewPart.setTabOrder(self.LE_Shank, self.LE_Diam_4)
        NewPart.setTabOrder(self.LE_Diam_4, self.CB_HeadOp)
        NewPart.setTabOrder(self.CB_HeadOp, self.LE_Diam_3)
        NewPart.setTabOrder(self.LE_Diam_3, self.LE_Diam_2)
        NewPart.setTabOrder(self.LE_Diam_2, self.LE_Mat)
        NewPart.setTabOrder(self.LE_Mat, self.LE_NumeroOp)
        NewPart.setTabOrder(self.LE_NumeroOp, self.tabWidget)
        NewPart.setTabOrder(self.tabWidget, self.LE_CodeOp)
        NewPart.setTabOrder(self.LE_CodeOp, self.LE_DescriptionOp)
        NewPart.setTabOrder(self.LE_DescriptionOp, self.PB_AddOp)
        NewPart.setTabOrder(self.PB_AddOp, self.PB_RemoveOp)
        NewPart.setTabOrder(self.PB_RemoveOp, self.TableOp)

    def retranslateUi(self, NewPart):
        _translate = QtCore.QCoreApplication.translate
        NewPart.setWindowTitle(_translate("NewPart", "Part Management"))
        self.groupBox.setTitle(_translate("NewPart", "Part Information :"))
        self.label_2.setText(_translate("NewPart", "Description :"))
        self.label.setText(_translate("NewPart", "Part Number :"))
        self.label_9.setText(_translate("NewPart", "Head Vol :"))
        self.label_13.setText(_translate("NewPart", "Estimate date : "))
        self.isStudBox.setText(_translate("NewPart", "Check if STUD"))
        self.label_18.setText(_translate("NewPart", "Designation :"))
        self.label_17.setText(_translate("NewPart", "Code :"))
        self.label_4.setText(_translate("NewPart", "Mfg Spec :"))
        self.isNutBox.setText(_translate("NewPart", "Check if NUT"))
        self.label_6.setText(_translate("NewPart", "Head Op :"))
        self.CB_HeadOp.setItemText(0, _translate("NewPart", "HotHead"))
        self.CB_HeadOp.setItemText(1, _translate("NewPart", "ColdHead"))
        self.CB_HeadOp.setItemText(2, _translate("NewPart", "ColdHeadUpset"))
        self.CB_HeadOp.setItemText(3, _translate("NewPart", "HotHeadUpset"))
        self.CB_HeadOp.setItemText(4, _translate("NewPart", "MachinePart"))
        self.label_3.setText(_translate("NewPart", "Revision :"))
        self.label_7.setText(_translate("NewPart", "Diameter :"))
        self.label_10.setText(_translate("NewPart", "Shank Lenght :"))
        self.label_8.setText(_translate("NewPart", "Part Weight :"))
        self.label_12.setText(_translate("NewPart", "Estimator :"))
        self.label_19.setText(_translate("NewPart", "Slug Length :"))
        self.CB_EstBy.setItemText(0, _translate("NewPart", "P.S"))
        self.CB_EstBy.setItemText(1, _translate("NewPart", "J.T"))
        self.CB_EstBy.setItemText(2, _translate("NewPart", "J.C"))
        self.label_5.setText(_translate("NewPart", "Material :"))
        self.groupBox_3.setTitle(_translate("NewPart", "Notes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("NewPart", "Part Information"))
        self.groupBox_2.setTitle(_translate("NewPart", "Operation"))
        self.label_14.setText(_translate("NewPart", "# :"))
        item = self.TableOp.verticalHeaderItem(0)
        item.setText(_translate("NewPart", "1"))
        item = self.TableOp.verticalHeaderItem(1)
        item.setText(_translate("NewPart", "2"))
        item = self.TableOp.verticalHeaderItem(2)
        item.setText(_translate("NewPart", "3"))
        item = self.TableOp.verticalHeaderItem(3)
        item.setText(_translate("NewPart", "4"))
        item = self.TableOp.verticalHeaderItem(4)
        item.setText(_translate("NewPart", "5"))
        item = self.TableOp.verticalHeaderItem(5)
        item.setText(_translate("NewPart", "6"))
        item = self.TableOp.verticalHeaderItem(6)
        item.setText(_translate("NewPart", "7"))
        item = self.TableOp.verticalHeaderItem(7)
        item.setText(_translate("NewPart", "8"))
        item = self.TableOp.verticalHeaderItem(8)
        item.setText(_translate("NewPart", "9"))
        item = self.TableOp.verticalHeaderItem(9)
        item.setText(_translate("NewPart", "10"))
        item = self.TableOp.verticalHeaderItem(10)
        item.setText(_translate("NewPart", "11"))
        item = self.TableOp.verticalHeaderItem(11)
        item.setText(_translate("NewPart", "12"))
        item = self.TableOp.verticalHeaderItem(12)
        item.setText(_translate("NewPart", "13"))
        item = self.TableOp.verticalHeaderItem(13)
        item.setText(_translate("NewPart", "14"))
        item = self.TableOp.verticalHeaderItem(14)
        item.setText(_translate("NewPart", "15"))
        item = self.TableOp.verticalHeaderItem(15)
        item.setText(_translate("NewPart", "16"))
        item = self.TableOp.verticalHeaderItem(16)
        item.setText(_translate("NewPart", "17"))
        item = self.TableOp.verticalHeaderItem(17)
        item.setText(_translate("NewPart", "18"))
        item = self.TableOp.verticalHeaderItem(18)
        item.setText(_translate("NewPart", "19"))
        item = self.TableOp.verticalHeaderItem(19)
        item.setText(_translate("NewPart", "20"))
        item = self.TableOp.verticalHeaderItem(20)
        item.setText(_translate("NewPart", "21"))
        item = self.TableOp.verticalHeaderItem(21)
        item.setText(_translate("NewPart", "22"))
        item = self.TableOp.verticalHeaderItem(22)
        item.setText(_translate("NewPart", "23"))
        item = self.TableOp.verticalHeaderItem(23)
        item.setText(_translate("NewPart", "24"))
        item = self.TableOp.verticalHeaderItem(24)
        item.setText(_translate("NewPart", "25"))
        item = self.TableOp.verticalHeaderItem(25)
        item.setText(_translate("NewPart", "26"))
        item = self.TableOp.verticalHeaderItem(26)
        item.setText(_translate("NewPart", "27"))
        item = self.TableOp.verticalHeaderItem(27)
        item.setText(_translate("NewPart", "28"))
        item = self.TableOp.verticalHeaderItem(28)
        item.setText(_translate("NewPart", "29"))
        item = self.TableOp.verticalHeaderItem(29)
        item.setText(_translate("NewPart", "30"))
        item = self.TableOp.verticalHeaderItem(30)
        item.setText(_translate("NewPart", "31"))
        item = self.TableOp.verticalHeaderItem(31)
        item.setText(_translate("NewPart", "32"))
        item = self.TableOp.verticalHeaderItem(32)
        item.setText(_translate("NewPart", "33"))
        item = self.TableOp.verticalHeaderItem(33)
        item.setText(_translate("NewPart", "34"))
        item = self.TableOp.verticalHeaderItem(34)
        item.setText(_translate("NewPart", "35"))
        item = self.TableOp.verticalHeaderItem(35)
        item.setText(_translate("NewPart", "36"))
        item = self.TableOp.verticalHeaderItem(36)
        item.setText(_translate("NewPart", "37"))
        item = self.TableOp.verticalHeaderItem(37)
        item.setText(_translate("NewPart", "38"))
        item = self.TableOp.verticalHeaderItem(38)
        item.setText(_translate("NewPart", "39"))
        item = self.TableOp.verticalHeaderItem(39)
        item.setText(_translate("NewPart", "40"))
        item = self.TableOp.horizontalHeaderItem(0)
        item.setText(_translate("NewPart", "Code"))
        item = self.TableOp.horizontalHeaderItem(1)
        item.setText(_translate("NewPart", "Operation"))
        item = self.TableOp.horizontalHeaderItem(2)
        item.setText(_translate("NewPart", "Setup"))
        item = self.TableOp.horizontalHeaderItem(3)
        item.setText(_translate("NewPart", "Cost"))
        self.PB_ValidateOperation.setText(_translate("NewPart", "Final Validate"))
        self.label_16.setText(_translate("NewPart", "Description :"))
        self.PB_AddOp.setText(_translate("NewPart", "Add Operation"))
        self.PB_RemoveOp.setText(_translate("NewPart", "Remove Operation"))
        self.PB_SaveOperation.setText(_translate("NewPart", "Save Progress"))
        self.label_15.setText(_translate("NewPart", "Code :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("NewPart", "Operation"))

